# Generated by Django 2.0.2 on 2018-04-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='shop.Cliente', verbose_name='Cliente '),
        ),
        migrations.AlterField(
            model_name='order',
            name='formapagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='shop.FormaPagamento', verbose_name='Forma de Pagamento '),
        ),
        migrations.AlterField(
            model_name='order',
            name='prazopagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='shop.PrazoPagamento', verbose_name='Prazo de Pagamento '),
        ),
    ]
